### ISSUE TITLE
Adding tags with leading number(s) will fail

### ISSUE THREAD

**Issue by saress** [terminal42/contao-node#10]
I've tried to add some new content-node tags and run into a problem.

`An exception occurred while executing 'INSERT INTO tl_cfg_tag_node (`node_id`, `cfg_tag_id`) VALUES ('38', '4-3s')': SQLSTATE[01000]: Warning: 1265 Data truncated for column 'cfg_tag_id' at row 1`

I added something like this: 4-3s, but I also tried 2-grid etc. Seems, that leading numbers cause some insert problems.

Best regards,
Sares

**Comment by qzminski** [comment]
This bug is strictly related to https://github.com/codefog/tags-bundle

I will open an issue in that repository where it belongs.
