### ISSUE TITLE
Missing table after installation

### ISSUE THREAD

**Issue by denniserdmann** [terminal42/contao-node#15]
As discussed with @richardhj, after installing contao-node, one have to update the database twice via the install tool. The table `tl_cfg_tag_node` is missing the first time.

**Comment by fritzmg** [comment]
afaik that's a Haste issue and happens with any m:n tables defined via Haste.

**Comment by qzminski** [comment]
This is very likely related to the Haste's Many-To-Many relation, but you are right it's incorrect two update the database two times… probably.

**Comment by denniserdmann** [comment]
ah ok.
