### ISSUE TITLE
Ability to select nodes in CTE and MOD by one (or multiple) tag names

### ISSUE THREAD

**Issue by scuben** [terminal42/contao-node#17]
What do you think about the possibility to not just use tags as a filter in the node selector but also the possibility to select one or multiple tags that will result in rendering all nodes with this tag in the frontend?

**Comment by Toflar** [comment]
Yeah, why not?

**Comment by Toflar** [comment]
I'm closing this, feel free to work on a solution if you need it. It sounds interesting :)
