### ISSUE TITLE
Define filters for each node

### ISSUE THREAD

**Issue by dmolineus** [terminal42/contao-node#2]
I evaluating to replace [psi/boxes4ward](https://github.com/psi-4ward/boxes4ward) with this extension. Boxes4ward isn't maintained really actively that's why I'm looking for an alterantive.

With boxes4ward it is possible to select pages as white- or blacklist on which the nodes should be visible. Also inherit this setting to supages is possible. 

Would you accept it as a feature? I'd provide a PR for it.

**Comment by Toflar** [comment]
That would only make sense for the FE module though, not for the CE, right?

**Comment by dmolineus** [comment]
You're right. The main purpose would be to use it in the FE module.

I could imagine use cases where it would be useful for CE as well. Let's think about following node structure:

- Layout sections `Folder`
    - Sidebar `Content` containing CE which has a reference to contact persons
   
- Contact persons `Folder`
   - Jane Doe `Content` uses the page filter
   - John Doe `Content` uses the page filter

I could make sense for such content as well, but I don't mind creating a FE module when needed.

**Comment by Toflar** [comment]
I think the use case is more for a module. Elements are not really here to be re-used which was the main idea behind this bundle anway :) One can still create a module and include that as an element if that's really desired. But for most of the users this setting will be confusing in the content element settings, I think. So I guess I'd accept a PR if it targets the FE module. @qzminski wdyt?

**Comment by qzminski** [comment]
A frontend module should be just fine for now, we can introduce that to content element settings in the future when it would be really needed. Right now it would be a bit too confusing IMO, especially that a frontend module seems more appropriate here.

**Comment by saress** [comment]
@dmolineus, @Toflar 
BTW:  if I do remember correctly, boxes4ward also supports some additional visibility-features like the possibility to show boxes on certain days of the week, certain months and I think also certain time-frames.

Maybe this would be also some useful features for a later release?

**Comment by Toflar** [comment]
I don't like these type of features. They are used very rarely and have a huge impact on caching. So that's very likely not going to make it into this bundle :)

**Comment by saress** [comment]
You are the caching-master, so no problem :-) 
I read about the extension yesterday and installed it minutes later. Great work and very useful!

**Comment by Toflar** [comment]
I'm not saying it's not possible to optimize things for caching but when things change visibility daily etc. the implementation just gets a lot harder :) We already have that problem with start and stop in Contao at various places and we still need to figure out what to do in that case so... :)
Thanks!

**Comment by saress** [comment]
I read your article about caching and all the problems and side-effects so I have a very small idea of what might go wrong :-)
