### ISSUE TITLE
Add more options

### ISSUE THREAD

**Issue by intradesign** [terminal42/contao-node#20]
Please add some more options to make the nodes a replacement for inserttags extension:

- Limit pages
- Show guests only
- Protect node

- Timing
- Condition
- Counter

Great would be the possibility to insert nodes directly in page layouts without having to create a module first and insert this module.

**Comment by fritzmg** [comment]
Simply provide a PR ;) 

> Great would be the possibility to insert nodes directly in page layouts without having to create a module first and insert this module.

You mean as a page type?

**Comment by intradesign** [comment]
Nein, ich meine als Frontend Modul im Seitenlayout.


*Jetzt mache ich es so:*Ich erstelle einen node (vorher: einen Artikel auf
einer nicht angezeigten Seite wie "Resources"), dann erstelle ich ein
Modul, das den node (bzw. bisher den Artikel) enthält. Dann füge ich das
Modul ins Seitenlayout als Frontend Modul ein.

Einfacher wäre es doch, wenn man die Nodes direkt als Frontend Modul
einbinden könnte. Das wären dann quasi Module, die von Redakteuren selbst
im Bereich Inhalte bearbteitet werden können.


*intradesign* / Timo Mackowiak / Husstäenweg 4 / 26629 Großefehn / Tel
0441-55979455 / Mobil 0173-5237884 / timo.mackowiak@intradesign.xyz /
USt-IdNr. DE259414283

Diese E-Mail könnte vertrauliche und/oder rechtlich geschützte
Informationen enthalten. Wenn Sie nicht der richtige Adressat sind oder
diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den
Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die
unbefugte Weitergabe dieser Mail sind nicht gestattet.

THINK before printing!


Am So., 26. Apr. 2020 um 11:01 Uhr schrieb Fritz Michael Gschwantner <
notifications@github.com>:

**Comment by fritzmg** [comment]
Es gibt doch bereits ein Frontend Modul. Was meinst du daher?

**Comment by intradesign** [comment]
Ich meine dass man die Nodes unter Themes -> Seitenlayout ->
Frontend-Module einbinden können sollte, für Nodes, die auf allen Seiten
erscheinen sollen, etwa Hinweise, die sich ggf. ändern. So könnte man sich
den Umweg über Themes -> Module sparen.

[image: image.png]

Am Mo., 27. Apr. 2020 um 12:56 Uhr schrieb Fritz Michael Gschwantner <
notifications@github.com>:

**Comment by fritzmg** [comment]
Imho that's not really worth the effort. Simply do it with the module, like with anything else in Contao.
