### ISSUE TITLE
Non-existent service

### ISSUE THREAD

**Issue by bytehead** [terminal42/contao-node#23]
I've updated `terminal42/contao-node` to version `1.3.0` and got this error:

```
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
                                                                               
  The service "terminal42_node.listener.data_container" has a dependency on a  
   non-existent service "codefog_tags.manager.terminal42_node". 
```

The `codefog/tags-bundle` is installed at version `3.1.1`.

**Comment by bytehead** [comment]
A downgrade solves the issue (temporarily):
```
codefog/tags-bundle (3.1.1 => 2.1.5)
terminal42/contao-node (1.3.0 => 1.1.3)
```

**Comment by qzminski** [comment]
I am not able to reproduce the issue 🤔 I assume you get that error in the backend, but where exactly? For me all views seem to work properly.

**Comment by bytehead** [comment]
I do get this on `composer update` during cache warmup.

**Comment by bytehead** [comment]
I don't use a managed edition - just the core-bundle in a plain Symfony project.

**Comment by fritzmg** [comment]
The change was introduced in https://github.com/terminal42/contao-node/commit/7f9ecbdf72f0575da26fab02fd877f3eabfd0331 - the missing service is now defined via the Contao Manager Plugin, which will only work in the Managed Edition.

**Comment by qzminski** [comment]
If you don't use a managed edition then you likely have to add the following configuration on the app level:

```yml
codefog_tags:
    managers:
        terminal42_node:
            source: 'tl_node.tags'
```

Please let me know if it worked, then I will add a necessary description to the README.

**Comment by bytehead** [comment]
Works perfectly 👌

**Comment by bytehead** [comment]
Thank you!
