### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by chriza** [terminal42/contao-node#27]
Contao 4.11.2
Nodes 1.3.3

Hallo,
User ohne Administartionsrechte haben immer mal wieder Schwierigkeiten Nodes wegen eines internen Serverfehlers aufzurufen.
Leider habe ich es noch nicht geschafft, den Fehler reproduzierbar herzustellen.

An exception occurred while executing 'SELECT DISTINCT `type` FROM tl_node WHERE id IN()': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1

Ich habe dazu ein Video angefertigt.
https://user-images.githubusercontent.com/1572887/115617696-01263a80-a2f2-11eb-87c8-09e8d0d98fbf.mp4

**Comment by Tastaturberuf** [comment]
Tritt das auch auf wenn der Redakteur sind regulär einloggt?

**Comment by chriza** [comment]
Ja.

**Comment by aschempp** [comment]
should be fixed by cda0f0a6d4a3dae42d86606bad4194488d87b617

**Comment by ngdot** [comment]
Habe das Problem auch unter der Version 1.4
Wenn ich bei dem betroffenen Benutzer die Session-Daten via Benutzerprofil lösche, geht es kurzfristig wieder.

```An exception occurred while executing 'SELECT DISTINCT `type` FROM tl_node WHERE id IN()': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1```
