### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ngdot** [terminal42/contao-node#28]
Habe das Problem auch unter der Version 1.4
Wenn ich bei dem betroffenen Benutzer die Session-Daten via Benutzerprofil lösche, geht es kurzfristig wieder.

```An exception occurred while executing 'SELECT DISTINCT `type` FROM tl_node WHERE id IN()': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1```

_Originally posted by @ngdot in https://github.com/terminal42/contao-node/issues/27#issuecomment-886574709_

**Comment by Toflar** [comment]
Kannst du erklären, wie ich das Problem reproduzieren kann?
