### ISSUE TITLE
Seitenauswahl hinzufügen?

### ISSUE THREAD

**Issue by operatorone** [terminal42/contao-node#30]
Besteht die Möglichkeit z. B. in der Node und/oder im Modul der Node eine Options-Gruppe für eine Seitenauswahl  hinzuzufügen. So kann individuell bestimmt werden, auf welchen Seiten der Node ausgegeben wird und man benötigt keine zusätzlichen Seitenlayouts, um die Zuordnung zu regeln.

![page-selection](https://user-images.githubusercontent.com/4036452/132230912-d7e8b657-e488-48ee-874d-f66c702269b1.jpg)

**Comment by Toflar** [comment]
Das würde dem Konzept völlig widersprechen. Die Idee von Node ist ja gerade andersrum: Pflege den Inhalt zentral an einem Ort und binde ihn dann via Seitenstruktur ein, wo auch immer du möchtest.

**Comment by operatorone** [comment]
Ok, danke für den Hinweis. Vielleicht habe ich es übersehen, aber wie kann ich die Seiten bestimmen, auf denen es angezeigt werden soll? Außer ich definiere ein Seitenlayout etc.

**Comment by Toflar** [comment]
Es geht um Inhalt. Das hat mit dem Seitenlayout nichts zu tun. Einfach das Inhaltselement "Nodes" im gewünschten Artikel auf der gewünschten Seite platzieren.

**Comment by operatorone** [comment]
Ok, verstehe. Danke.
