### ISSUE TITLE
Missing German translation: Access protection

### ISSUE THREAD

**Issue by contaoacademy** [terminal42/contao-node#31]
The translation for label "Access protection" is missing.

![screen-20210930_cpDq1C8j](https://user-images.githubusercontent.com/23719181/135399848-e99e62bd-a5fc-4a0e-9a0d-202f1a60a2db.jpg)

**Comment by Toflar** [comment]
Fixed in https://github.com/terminal42/contao-node/commit/9a94b543cd6d9ae5602df2813c19b345ebadb58f and released as 1.5.1.
