### ISSUE TITLE
Error: Column not found: 1054 Unknown column 'tags' in 'field list'

### ISSUE THREAD

**Issue by design23** [terminal42/contao-node#36]
While trying to save a new entry, this error appears:

An exception occurred while executing 'UPDATE tl_node SET `tags`=NULL WHERE id='1'': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tags' in 'field list'

Contao 4.9.25
contao-node: Version 1.5.2

**Comment by Tastaturberuf** [comment]
Have you updated the database after install the bundle?

**Comment by design23** [comment]
Yes. No changes at all.

**Comment by Tastaturberuf** [comment]
cleared the cache before update?

**Comment by design23** [comment]
Yup.

**Comment by design23** [comment]
Just recognized, that the top right button for the backend user profile doesn't work as soon as I enter the "Nodes" section. Interesting ;)

**Comment by Tastaturberuf** [comment]
i think another Extension causes the problem

**Comment by design23** [comment]
Ok, gonna check it and give you feedback next week.

**Comment by fritzmg** [comment]
This is an error in Contao 4.9.25: https://github.com/contao/contao/pull/4067

**Comment by Toflar** [comment]
Closing then because it's not an issue in the extension :)
