### ISSUE TITLE
The folder nodes are not allowed

### ISSUE THREAD

**Issue by ameotoko** [terminal42/contao-node#38]
If you select a node of type `folder` in content element "Nodes", you get this error: `The folder nodes are not allowed`. Should folders not be selectable then? Or is it something the picker currently cannot do? 🤔

**Comment by qzminski** [comment]
The folder nodes are not allowed to be selected, thus this error is displayed. We cannot make them "unselectable" in the picker, because it's currently not supported in Contao.
