### ISSUE TITLE
Vererbung der Node Mounts wird nicht berücksichtigt

### ISSUE THREAD

**Issue by gieby** [terminal42/contao-node#39]
**System**:
CONTAO: 4.9.28
contao-node: 1.5.6

**Beschreibung**:
Wenn man einem Benutzer einen Mountpoint auf einen Ordner gibt und dieser anschließend den Fokus auf ein Inhaltsfragment legt, erscheint folgende Fehlermeldung:  

`An exception occurred while executing 'SELECT DISTINCT 'type' FROM tl_node WHERE id IN()': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1`

**Schritte zum reproduzieren**:
1. einen Ordner-Node anlegen
2. in diesem einen Inhalts-Node anlegen
3. einem Benutzer nur den Ordner-Node als Node-Mount geben
4. mit diesem Benutzer auf den Namen des Inhalts-Nodes klicken, um ihn zu "fokussieren"

Vermutlich beziehen sich die Bugs #27 und #28 ebenfalls auf dieses Verhalten. Zumindest ist die Fehlermeldung die gleiche.

**Comment by qzminski** [comment]
Do you mean a configuration like this?

<img width="408" alt="CleanShot 2022-10-31 at 12 51 42" src="https://user-images.githubusercontent.com/193483/199001613-fe6a6db9-74dc-4552-bfd5-aa6e8e838d8a.png">

<img width="589" alt="CleanShot 2022-10-31 at 12 52 08" src="https://user-images.githubusercontent.com/193483/199001665-1653dd4d-3252-4832-b71a-ee08bb2c36d2.png">

**Comment by gieby** [comment]
Yes, that's the configuration.

Additionally it seems that if you put the focus on the folder mount the content nodes won't show up.

**Comment by qzminski** [comment]
Okay, then I'm not able to reproduce that. Would you be able to send me your database to kamil.kuzminski@gmail.com?
