### ISSUE TITLE
Contao 5.04: Non-existent service "session".

### ISSUE THREAD

**Issue by kikmedia** [terminal42/contao-node#43]
On a clean Contao 5.04 installation I get the following with Nodes v 1.5.11:
`The service "terminal42_node.listener.data_container" has a dependency on a  
   non-existent service "session". Did you mean one of these: "argument_resol  
  ver.session", "session.storage.factory.native", "session_listener", "securi  
  ty.authentication.session_strategy", "security.listener.session.contao_back  
  end", "security.logout.listener.session.contao_backend", "security.listener  
  .session.contao_frontend", "security.logout.listener.session.contao_fronten  
  d", "contao.listener.clear_session_data", "contao.listener.user_session", "  
  contao.session.factory", "contao.session.contao_backend", "contao.session.c  
  ontao_frontend", "contao.session.factory.inner"?`

Any clues for me?

**Comment by Toflar** [comment]
Yes, that's a bug!

**Comment by Toflar** [comment]
https://github.com/terminal42/contao-node/blob/a5cce9aa9f5ea034170f3c1593ec18867648ebad/src/Resources/config/services.yml#L22

**Comment by qzminski** [comment]
Should be fixed in 9f2cfda and 1.5.12.
