### ISSUE TITLE
Version 1.5.13 not installable in contao 4.13

### ISSUE THREAD

**Issue by OMOSde** [terminal42/contao-node#45]
Contao 4.13
Php 8.1
Fresh installation (console)

Error message: `Fatal error: Declaration of Terminal42\NodeBundle\Picker\NodePickerProvider::supportsContext(string $context): bool must be compatible with Contao\CoreBundle\Picker\PickerProviderInterface::supportsContext($context) in C:\Laragon\www\wguw-wgu-wismar.de\vendor\terminal42\contao-node\src\Picker\NodePickerProvider.php on line 70`

Maybe introduced by https://github.com/terminal42/contao-node/commit/8dc6f833edd4dee62f82c3a255c7f5a70df6d853 ?

**Comment by mlwebworker** [comment]
Habe den gleichen Fehler nach dem Update auf Contao 4.13.10 auf 4.13.12 und dem Update  von contao-nodes auf Version 1.5.13

**Comment by OMOSde** [comment]
Ich habe in der composer.json einen Konflikt eingetragen:

`"terminal42/contao-node": "1.5.11 || 1.5.12 || 1.5.13"`

**Comment by qzminski** [comment]
It should be fixed now, please update the extension again.

**Comment by mlwebworker** [comment]
Just tested in one installation. It runs without any problems. Thanks
