### ISSUE TITLE
Show node name in article listing of content elements

### ISSUE THREAD

**Issue by saress** [terminal42/contao-node#6]
If you add a content node as a content-element to your articles, it shows the content of the node's first content element in the listing as description. I think it would be better, if the "name" of the node would be displayed instead.

Hope it is clear what I mean :-)

If not: 
- create a new content node
- name it f.e. "testnode" and add some content elements to it
- go to articles and add the testnode to an article
- in the listing you will see, that it will not show "Nodes -> testnode", but the content of the first generated content element, whatever it is f.ex. "Nodes -> Some text".

Kind regards,
Sares

**Comment by Toflar** [comment]
I agree, we should optimize that for the back end. 👍

**Comment by saress** [comment]
👍

**Comment by qzminski** [comment]
Implemented in fc88b30.

**Comment by saress** [comment]
@qzminski: I have tested it in the dev-branch (works fine) and have updated right now to V 1.0.2.
Seems, that the release doesn't include the implementation?

**Comment by qzminski** [comment]
@saress the new feature is currently on develop branch which means it will be released once version 1.1.0 is out.

@Toflar are we good to release 1.1.0?

**Comment by saress** [comment]
@qzminski: ah ok, thank you, I didn't know that.

**Comment by Toflar** [comment]
> @Toflar are we good to release 1.1.0?

Not yet, there seems to be some issue still with copying and I just merged the German translation. I created a milestone, feel free to release and close it once that copying thing is resolved 😄
