### ISSUE TITLE
Limit access of node content elements to specific user-groups

### ISSUE THREAD

**Issue by saress** [terminal42/contao-node#7]
Nowadays, your articles often look like this:

-wrapper start
---grid start
-----text-element
---grid stop
---grid start
-----gallery-element 
---grid stop
-wrapper stop
...

To have the possibility now to organize things like that in virtual folders and nodes is a big improvement and will reduce complexity in the articles-listing a lot.

However, normally, editors should only have access to the "inner" elements "text" and "gallery" in most cases, as shown in the example above. So maybe the bundle could be extended to define, if a content element should be visible / editable by a user/user-group or not.

If so, editing the node will result in a listing like this:

-----text-element
-----gallery-element 

and the "complexity" of the outer structure will be hidden and a lot of admins would sleep much better I think :-)

What do you think?

Kind regards,
Sares

**Comment by Toflar** [comment]
That's content element access. That's not related to this bundle at all and it already exists anyway :)
https://extensions.contao.org/#/?q=terminal42%2Fcontao-ce-access

**Comment by saress** [comment]
I will have a look at it, thank you!

**Comment by saress** [comment]
I have installed ce-access and played around a bit, very nice and mighty extension :-)
But I think you will not be able to do the things described above.

With ce-access you either can activate some content element(s) or not. 
Elements that are not activated will be displayed as described above and you only can't edit or delete it, but copy and move them as you like and they stay in place where they are defined. If you wanna disable a specific element f.ex. a "text" element, you just can disable text-elements at all, but they will stay visible in the node.

My scenario starts a level deeper I think , so it's the "specific" text element, that should be disabled / hidden for editors and not text elements "at all".

But maybe I have missed something here :-)

**Comment by Toflar** [comment]
Still it's a feature entirely not related to this bundle.

**Comment by saress** [comment]
I think it mainly depends on what you have in mind when you start planning & developing this bundle and my scenario is a bit "special", I agree ;-)
