### ISSUE TITLE
Feature import/export

### ISSUE THREAD

**Issue by fkaminski** [terminal42/contao-node#8]
Schön wäre eine Import/Export Möglichkeit ala .cto  zur Nutzung in versch. Installationen.
Wäre dies technisch überhaupt möglich?

**Comment by fritzmg** [comment]
https://github.com/contao/contao/issues/402

**Comment by fkaminski** [comment]
> [contao/contao#402](https://github.com/contao/contao/issues/402)

Noch besser ...
