### ISSUE TITLE
Copy node doesn't copy content elements

### ISSUE THREAD

**Issue by saress** [terminal42/contao-node#9]
I don't know if this is a bug or a non-existing feature :-)

If you make a copy of an existing node the included content elements are not copied and the new node has no content elements at all.

Best regards,
Sares

**Comment by saress** [comment]
@qzminski: Works, thank you!

**Comment by saress** [comment]
@qzminski: I run into a problem when copying a content-node, editing and saving it:

`An exception occurred while executing 'INSERT INTO tl_cfg_tag (`tstamp`, `name`, `source`) VALUES (1564121024, 'header', 'terminal42_node')': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry `

If I do another "Save" the error disappears.

**Comment by saress** [comment]
@qzminski: I have just recognized, that it also happens if I add a new entry:

`An exception occurred while executing 'INSERT INTO tl_cfg_tag (`tstamp`, `name`, `source`) VALUES (1564121831, 'content', 'terminal42_node')': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry `

I guess, it is related to the tags-bundle, right? 
I will reference it here also: https://github.com/codefog/tags-bundle

Thanks!

**Comment by qzminski** [comment]
Closing in favor of https://github.com/codefog/tags-bundle/issues/19.
